In [1]:
import numpy as np

# Hidden States
states = ["Walking", "Running", "Resting"]

# Observation symbols
obs_symbols = ["Low", "Medium", "High"]

# Initial probabilities
pi = np.array([0.5, 0.3, 0.2])

# Transition matrix
A = np.array([
    [0.6, 0.3, 0.1],
    [0.2, 0.5, 0.3],
    [0.3, 0.2, 0.5]
])

# Emission matrix
B = np.array([
    [0.6, 0.3, 0.1],
    [0.1, 0.3, 0.6],
    [0.7, 0.2, 0.1]
])

# Observation sequence: High, Medium, Low, High
observations = ["High", "Medium", "Low", "High"]

# Convert observations to indices
obs_index = {v: i for i, v in enumerate(obs_symbols)}
O = [obs_index[o] for o in observations]

T = len(O)
N = len(states)

# Forward Algorithm
alpha = np.zeros((T, N))

# Initialization
alpha[0] = pi * B[:, O[0]]

# Induction
for t in range(1, T):
    for j in range(N):
        alpha[t, j] = np.sum(alpha[t-1] * A[:, j]) * B[j, O[t]]

# Termination
probability = np.sum(alpha[T-1])

print("Forward Probability Table:\n")
for t in range(T):
    print(f"Time {t+1}: {alpha[t]}")

print("\nLikelihood of Observation Sequence =", probability)

Forward Probability Table:

Time 1: [0.05 0.18 0.02]
Time 2: [0.0216 0.0327 0.0138]
Time 3: [0.014184 0.002559 0.013209]
Time 4: [0.00129849 0.0049059  0.00087906]

Likelihood of Observation Sequence = 0.007083450000000001


In [3]:
pip install hmmlearn

In [4]:
import numpy as np
from hmmlearn import hmm

# Observation encoding
obs_symbols = {"Low":0, "Medium":1, "High":2}

# Observation sequence
obs = np.array([[2],[1],[0],[2]])

# HMM Model
model = hmm.CategoricalHMM(n_components=3, init_params="")

# Initial Probabilities
model.startprob_ = np.array([0.5,0.3,0.2])

# Transition Matrix
model.transmat_ = np.array([
    [0.6,0.3,0.1],
    [0.2,0.5,0.3],
    [0.3,0.2,0.5]
])

# Emission Matrix
model.emissionprob_ = np.array([
    [0.6,0.3,0.1],
    [0.1,0.3,0.6],
    [0.7,0.2,0.1]
])

# Likelihood
log_prob = model.score(obs)
print("Log Likelihood =", log_prob)
print("Likelihood =", np.exp(log_prob))

# Other Observation Sequences
sequences = {
    "O1":[0,1,2,1],
    "O2":[2,2,2,2],
    "O3":[0,0,0,0],
    "O4":[1,1,1,1]
}

print("\nLikelihoods:\n")

for name, seq in sequences.items():
    x = np.array(seq).reshape(-1,1)
    lp = model.score(x)
    print(name, "=", np.exp(lp))

# Predict Hidden States
hidden = model.predict(obs)

state_names = ["Walking","Running","Resting"]

print("\nPredicted Hidden States:")
for s in hidden:
    print(state_names[s])

# Baum-Welch Training
train_model = hmm.CategoricalHMM(
    n_components=3,
    n_iter=20,
    random_state=42
)

train_model.fit(obs)

print("\nLearned Initial Probabilities")
print(train_model.startprob_)

print("\nLearned Transition Matrix")
print(train_model.transmat_)

print("\nLearned Emission Matrix")
print(train_model.emissionprob_)

Fitting a model with 14 free scalar parameters with only 4 data points will result in a degenerate solution.


Log Likelihood = -4.949994201827224
Likelihood = 0.007083450000000005

Likelihoods:

O1 = 0.009616449999999995
O2 = 0.008572950000000005
O3 = 0.05358868000000001
O4 = 0.005911780000000002

Predicted Hidden States:
Running
Walking
Walking
Running

Learned Initial Probabilities
[0. 0. 1.]

Learned Transition Matrix
[[0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [7.39796078e-18 0.00000000e+00 1.00000000e+00]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00]]

Learned Emission Matrix
[[0.00000000e+00 1.00000000e+00 7.39796078e-18]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
